name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test
        env:
          CI: true
          SESSION_SECRET: test
          DGFIP_API_HOST: https://fournisseur-de-donnees.dev-franceconnect.fr/situations/ir/assiettes/annrev/2018
          FC_ISSUER: https://fcp.integ01.dev-franceconnect.fr
          FC_AUTHORIZATION_ENDPOINT: https://fcp.integ01.dev-franceconnect.fr/api/v1/authorize
          FC_TOKEN_ENDPOINT: https://fcp.integ01.dev-franceconnect.fr/api/v1/token
          FC_USERINFO_ENDPOINT: https://fcp.integ01.dev-franceconnect.fr/api/v1/userinfo
          FC_CLIENT_ID: 211286433e39cce01db448d80181bdfd005554b19cd51b3fe7943f6b3b86ab6e
          FC_CLIENT_SECRET: 2791a731e6a59f56b6b4dd0d08c9b1f593b5f3658b9fd731cb24248e2669af4b
          FC_REDIRECT_URI: http://localhost:3000/login-callback
